### PR TITLE
Stud 11 - Added basic login/register forms

### PR DESCRIPTION
**Pull request by jamilgonzalez**
<h3>Register</h3>

Screen Shot 2021-02-17 at 9 34 10 AM

<h3>Login</h3>

Screen Shot 2021-02-17 at 9 35 10 AM

<hr />

* Waiting on API to connect forms to db
*  Until then next tix will be focused on creating global user state and an api call hook to make formatting api requests to our service easier and less verbose in components.

### CODE REVIEW

**Comment by Deadcoast** [comment]
TEst

**Comment by nolaaaaaan** [comment]
-I like

**Comment by nolaaaaaan** [comment]
- I like

**Comment by TroyMorgan1205** [comment]
test

**Review by janto393 — APPROVED** [review]
Looks Good

**Pull request merged**
