### PR TITLE
login/register

### PR DESCRIPTION
**Pull request by jamilgonzalez**
** Need CORS solution from backend. Currently blocked at connecting apis to front-end calls
* This handles user register state (will be modified in the future to encompass general user state when we have a 200 for register/login)

### CODE REVIEW

**Comment by Deadcoast** [comment]
@jamilgonzalez Here is the cors logic. Insert this into the backend's `index.ts` file between the statements `app.use(bodyParser.json())` and `app.get('/', ...`

You can also look at my branch `events-frontend` to see how it was integrated into the backend's `index.ts`

```javascript
// Access Control Logic
app.use((request: Request, response: Response, next: CallableFunction) => 
{
  response.setHeader('Access-Control-Allow-Origin', '*');
  response.setHeader(
    'Access-Control-Allow-Headers',
    'Origin, X-requestuested-With, Content-Type, Accept, Authorization'
  );
  response.setHeader(
    'Access-Control-Allow-Methods',
    'GET, POST, PATCH, DELETE, OPTIONS'
  );
  next();
}); 
```

**Review by janto393 — CHANGES_REQUESTED** [review]
@jamilgonzalez Here is the cors logic. Insert this into the backend's `index.ts` file between the statements `app.use(bodyParser.json())` and `app.get('/', ...`

You can also look at my branch `events-frontend` to see how it was integrated into the backend's `index.ts`

```javascript
// Access Control Logic
app.use((request: Request, response: Response, next: CallableFunction) => 
{
  response.setHeader('Access-Control-Allow-Origin', '*');
  response.setHeader(
    'Access-Control-Allow-Headers',
    'Origin, X-requestuested-With, Content-Type, Accept, Authorization'
  );
  response.setHeader(
    'Access-Control-Allow-Methods',
    'GET, POST, PATCH, DELETE, OPTIONS'
  );
  next();
}); 
```

**Comment by jamilgonzalez** [comment]
Most recent master was merged in as requested 👍

**Review by janto393 — APPROVED** [review]
Looks good.

The only thing that doesn't sit well with me, albeit minor, is that your files are not being terminated with a newline. This can be fixed by adding the settings field 
```json
"files.insertFinalNewline": true,
````
to your settings.json file in VS code.

**Pull request merged**
